services:
  db:
    image: postgres:17-alpine
    container_name: sgpt_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sgpt_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sgpt_backend
    restart: always
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - sgpt_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: sgpt_frontend
    restart: always
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - sgpt_network

networks:
  sgpt_network:
    driver: bridge

volumes:
  postgres_data:
